'use strict';

window.addEventListener('DOMContentLoaded', () => {
  const results = [];
  const check = (name, condition) => {
    results.push(`${condition ? 'PASS' : 'FAIL'} ${name}`);
    if (!condition) throw new Error(name);
  };
  const click = selector => document.querySelector(selector).click();
  const change = (id, value) => { document.getElementById(id).value = value; document.getElementById(id).dispatchEvent(new Event('change', { bubbles: true })); };
  try {
    check('Initial login visible and store hidden', !document.getElementById('login-screen').hidden && document.getElementById('main-app').hidden);
    check('Legacy cart image paths migrate with quantities', cart.length === 1 && cart[0].cantidad === 2 && cart[0].imagen === 'assets/images/angel.jpg');
    document.getElementById('login-email').value = 'admin@admin.com';
    document.getElementById('login-pass').value = 'incorrect';
    document.getElementById('login-form').requestSubmit();
    check('Incorrect administrator password rejected', !currentSession && !document.getElementById('login-error').hidden);
    document.getElementById('login-pass').value = 'admin123';
    document.getElementById('login-form').requestSubmit();
    check('Original administrator credentials and panel restored', currentSession.role === 'admin' && !document.getElementById('admin-panel').hidden);
    check('Administration starts closed and outside the store', !document.getElementById('admin-panel').open && !document.querySelector('#main-app #admin-panel'));
    document.getElementById('open-admin').click();
    check('Administrator can open separate panel', document.getElementById('admin-panel').open);
    check('Previous order history remains available', document.getElementById('orders-tbody').textContent.includes('Cliente anterior'));
    click('[data-order="100"]');
    check('Previous order details open safely', document.getElementById('order-dialog').open && document.getElementById('order-detail').textContent.includes('Cliente anterior'));
    document.getElementById('order-dialog').close();
    document.getElementById('admin-panel').close();
    const savedSession = JSON.parse(sessionStorage.getItem('miga_session'));
    check('Session persisted without password', savedSession.role === 'admin' && !JSON.stringify(savedSession).includes('admin123'));
    document.getElementById('btn-logout').click();
    check('Logout preserves cart and hides administration', !currentSession && cart[0].cantidad === 2 && document.getElementById('admin-panel').hidden && !document.getElementById('login-screen').hidden);
    document.getElementById('login-email').value = 'cliente@demo.com';
    document.getElementById('login-pass').value = 'incorrecta';
    document.getElementById('login-form').requestSubmit();
    check('Wrong demo client password rejected', !currentSession && !document.getElementById('login-error').hidden);
    document.getElementById('login-email').value = 'desconocido@ejemplo.com';
    document.getElementById('login-pass').value = 'cliente123';
    document.getElementById('login-form').requestSubmit();
    check('Unknown account rejected', !currentSession);
    document.getElementById('login-email').value = 'cliente@demo.com';
    document.getElementById('login-pass').value = 'cliente123';
    document.getElementById('login-form').requestSubmit();
    check('Client login restored', currentSession.role === 'user' && document.getElementById('admin-panel').hidden);
    check('Customer cannot see administration or business orders', document.getElementById('open-admin').hidden && getComputedStyle(document.getElementById('admin-panel')).display === 'none' && document.getElementById('orders-tbody').textContent === '');
    document.getElementById('open-admin').click();
    showOrder('100');
    check('Customer cannot open administration or another customer order', !document.getElementById('admin-panel').open && !document.getElementById('order-dialog').open);
    check('Complete catalog preserved', products.length === 64 && document.querySelectorAll('.product').length === 64);
    check('All four menu headings restored', document.querySelectorAll('.menu-group-heading').length === 4 && document.getElementById('titulo-calientes').textContent === 'Bebidas calientes' && document.getElementById('titulo-frias').textContent === 'Bebidas frías');
    cart = []; saveCart();
    document.getElementById('quantity-0').value = 3;
    click('[data-add="0"]');
    check('Product quantity adds expected total', cart[0].cantidad === 3 && total() === 150);
    document.getElementById('floating-cart').click();
    check('Floating cart opens cart dialog', document.getElementById('cart-dialog').open);
    const quantityInput = document.querySelector('[data-quantity="0"]');
    quantityInput.value = 4; quantityInput.dispatchEvent(new Event('change', { bubbles: true }));
    check('Direct cart quantity updates subtotal and badge', total() === 200 && document.getElementById('floating-count').textContent === '4' && document.getElementById('floating-total').textContent === money(200));
    const invalidInput = document.querySelector('[data-quantity="0"]');
    invalidInput.value = 0; invalidInput.dispatchEvent(new Event('change', { bubbles: true }));
    check('Invalid cart quantity rejected', cart[0].cantidad === 4);
    document.getElementById('cart-dialog').close();
    window.scrollTo(0, document.body.scrollHeight);
    const bounds = document.getElementById('floating-cart').getBoundingClientRect();
    check('Cart stays visible after scrolling', getComputedStyle(document.getElementById('floating-cart')).position === 'fixed' && bounds.top >= 0 && bounds.bottom <= innerHeight && bounds.left >= 0 && bounds.right <= innerWidth);
    change('quick-payment', 'transferencia');
    document.getElementById('open-cart').click(); document.getElementById('checkout-button').click();
    check('Quick payment retained in checkout', document.getElementById('payment-method').value === 'transferencia' && !document.getElementById('transfer-details').hidden);
    check('Original bank information restored', document.getElementById('transfer-details').textContent.includes('4152 3144 4143 5370'));
    check('Pickup does not require address', !document.getElementById('address').required);
    change('delivery', 'domicilio');
    check('Delivery requires address', document.getElementById('address').required && !document.getElementById('address-label').hidden);
    const transfer = new DataTransfer();
    transfer.items.add(new File(['test receipt'], 'comprobante.pdf', { type: 'application/pdf' }));
    document.getElementById('comprobante').files = transfer.files;
    document.getElementById('comprobante').dispatchEvent(new Event('change'));
    check('Receipt preview restored', !document.getElementById('receipt-preview').hidden && document.getElementById('receipt-preview').href.startsWith('blob:'));
    const form = document.getElementById('checkout-form');
    form.elements.nombre.value = 'Cliente de prueba';
    form.elements.telefono.value = '2321234567';
    form.elements.direccion.value = 'Calle de prueba 123';
    let openedURL = '';
    window.open = url => { openedURL = url; };
    form.requestSubmit();
    check('WhatsApp summary generated without sending', openedURL.startsWith('https://wa.me/522321237364?text=') && decodeURIComponent(openedURL).includes('Cliente de prueba'));
    check('New pending order appended without losing previous order', readOrders().length === 2 && readOrders()[0].cliente === 'Cliente anterior');
    form.requestSubmit();
    check('Repeated handoff does not duplicate order', readOrders().length === 2);
    check('Cart persists after WhatsApp handoff', JSON.parse(localStorage.getItem('miga_cart'))[0].cantidad === 4);
    document.getElementById('checkout-dialog').close();
    document.getElementById('open-orders').click();
    check('Customer can view own request only', document.getElementById('history-dialog').open && document.getElementById('customer-orders').textContent.includes('Solicitud preparada') && !document.getElementById('customer-orders').textContent.includes('Cliente anterior'));
    document.getElementById('history-dialog').close();
    const search = document.getElementById('search'); search.value = 'cafe'; search.dispatchEvent(new Event('input'));
    check('Search ignores accents', document.querySelectorAll('.product').length > 0 && document.querySelectorAll('.product').length < products.length);
    search.value = ''; search.dispatchEvent(new Event('input'));
    click('[data-category="bebidas"]');
    check('Category filter remains functional', document.querySelectorAll('.product').length === products.filter(p => p.category === 'bebidas').length);
    check('Drinks show hot and cold headings only', document.querySelectorAll('.menu-group').length === 2 && !document.getElementById('titulo-postres'));
    const hotSection = document.getElementById('titulo-calientes').closest('.menu-group');
    const coldSection = document.getElementById('titulo-frias').closest('.menu-group');
    check('Drink sections preserve original classification', hotSection.textContent.includes('Café Americano') && !hotSection.textContent.includes('Frappe de Oreo') && coldSection.textContent.includes('Frappe de Oreo') && !coldSection.textContent.includes('Café Americano'));
    change('sort', 'asc');
    let correctlySorted = true;
    for (const group of document.querySelectorAll('.menu-group')) {
      const prices = Array.from(group.querySelectorAll('[data-add]'), button => products[Number(button.dataset.add)].precio);
      if (prices.some((price, index) => index > 0 && price < prices[index - 1])) correctlySorted = false;
    }
    check('Price sorting works within each menu section', correctlySorted);
    search.value = 'producto inexistente'; search.dispatchEvent(new Event('input'));
    check('Empty search has no empty category headings', document.querySelectorAll('.menu-group').length === 0 && document.getElementById('products').textContent.includes('No encontramos'));
    search.value = ''; search.dispatchEvent(new Event('input'));
    click('[data-story]');
    check('Expanded stories restored', document.getElementById('story-dialog').open && document.getElementById('story-image').src.includes('chocoflan.jpg'));
    document.getElementById('story-dialog').close();
    const previousSlide = slideIndex;
    document.getElementById('carousel-next').click();
    check('Carousel navigation restored', slideIndex === (previousSlide + 1) % slides.length);
    carouselPaused = true; scheduleCarousel();
    window.confirm = () => false;
    document.getElementById('clear-cart').click();
    check('Cancel clear cart preserves contents', cart.length === 1);
    window.confirm = () => true;
    document.getElementById('clear-cart').click();
    check('Clear cart updates all controls', !cart.length && document.getElementById('checkout-button').disabled && document.getElementById('floating-count').textContent === '0');
    check('No horizontal page overflow', document.documentElement.scrollWidth <= innerWidth);
    document.getElementById('btn-logout').click(); document.getElementById('login-as-user').click();
    check('Guest entry restored', currentSession.role === 'user' && !document.getElementById('main-app').hidden);
    check('Guest cannot see administration', document.getElementById('open-admin').hidden && !document.getElementById('admin-panel').open && document.getElementById('admin-panel').hidden);
    document.getElementById('btn-logout').click();
    document.getElementById('login-demo-client').click();
    check('Demo shortcut opens the client account without administration', currentSession.email === 'cliente@demo.com' && currentSession.role === 'user' && document.getElementById('open-admin').hidden);
    document.getElementById('open-orders').click();
    check('Demo account retains its requests after signing in again', document.getElementById('customer-orders').textContent.includes('Solicitud preparada'));
    document.getElementById('history-dialog').close();
    check('Original PDF and map preserved', Boolean(document.querySelector('a[download][href^="assets/documents/"]')) && Boolean(document.querySelector('#ubicacion iframe')));
  } catch (error) {
    results.push('FAIL ' + error.message);
  }
  clearInterval(carouselTimer);
  document.querySelectorAll('dialog[open]').forEach(dialog => dialog.close());
  const report = document.createElement('pre');
  report.id = 'verification-results';
  report.textContent = results.join('\n');
  document.body.prepend(report);
  document.title = results.some(result => result.startsWith('FAIL')) ? 'FAIL regression' : 'PASS regression';
  window.scrollTo(0, 0);
});
