'use strict';

window.addEventListener('DOMContentLoaded', () => {
  const results = [];
  const check = (name, condition) => {
    results.push(`${condition ? 'PASS' : 'FAIL'} ${name}`);
    if (!condition) throw new Error(name);
  };
  const click = selector => document.querySelector(selector).click();
  const change = (id, value) => { $(id).value = value; $(id).dispatchEvent(new Event('change', { bubbles: true })); };
  try {
    check('Initial login visible and store hidden', !$('login-screen').hidden && $('main-app').hidden);
    check('Legacy cart image paths migrate with quantities', cart.length === 1 && cart[0].cantidad === 2 && cart[0].imagen === 'assets/images/angel.jpg');
    $('login-email').value = 'admin@admin.com';
    $('login-pass').value = 'incorrect';
    $('login-form').requestSubmit();
    check('Incorrect administrator password rejected', !currentSession && !$('login-error').hidden);
    $('login-pass').value = 'admin123';
    $('login-form').requestSubmit();
    check('Original administrator credentials and panel restored', currentSession.role === 'admin' && !$('admin-panel').hidden);
    check('Previous order history remains available', $('orders-tbody').textContent.includes('Cliente anterior'));
    click('[data-order="100"]');
    check('Previous order details open safely', $('order-dialog').open && $('order-detail').textContent.includes('Cliente anterior'));
    $('order-dialog').close();
    const savedSession = JSON.parse(sessionStorage.getItem('miga_session'));
    check('Session persisted without password', savedSession.role === 'admin' && !JSON.stringify(savedSession).includes('admin123'));
    $('btn-logout').click();
    check('Logout preserves cart and hides administration', !currentSession && cart[0].cantidad === 2 && $('admin-panel').hidden && !$('login-screen').hidden);
    $('login-email').value = 'cliente@ejemplo.com';
    $('login-pass').value = 'demo';
    $('login-form').requestSubmit();
    check('Client login restored', currentSession.role === 'user' && $('admin-panel').hidden);
    check('Complete catalog preserved', products.length === 64 && document.querySelectorAll('.product').length === 64);
    cart = []; saveCart();
    $('quantity-0').value = 3;
    click('[data-add="0"]');
    check('Product quantity adds expected total', cart[0].cantidad === 3 && total() === 150);
    $('floating-cart').click();
    check('Floating cart opens cart dialog', $('cart-dialog').open);
    const quantityInput = document.querySelector('[data-quantity="0"]');
    quantityInput.value = 4; quantityInput.dispatchEvent(new Event('change', { bubbles: true }));
    check('Direct cart quantity updates subtotal and badge', total() === 200 && $('floating-count').textContent === '4' && $('floating-total').textContent === money(200));
    const invalidInput = document.querySelector('[data-quantity="0"]');
    invalidInput.value = 0; invalidInput.dispatchEvent(new Event('change', { bubbles: true }));
    check('Invalid cart quantity rejected', cart[0].cantidad === 4);
    $('cart-dialog').close();
    window.scrollTo(0, document.body.scrollHeight);
    const bounds = $('floating-cart').getBoundingClientRect();
    check('Cart stays visible after scrolling', getComputedStyle($('floating-cart')).position === 'fixed' && bounds.top >= 0 && bounds.bottom <= innerHeight && bounds.left >= 0 && bounds.right <= innerWidth);
    change('quick-payment', 'transferencia');
    $('open-cart').click(); $('checkout-button').click();
    check('Quick payment retained in checkout', $('payment-method').value === 'transferencia' && !$('transfer-details').hidden);
    check('Original bank information restored', $('transfer-details').textContent.includes('4152 3144 4143 5370'));
    check('Pickup does not require address', !$('address').required);
    change('delivery', 'domicilio');
    check('Delivery requires address', $('address').required && !$('address-label').hidden);
    const transfer = new DataTransfer();
    transfer.items.add(new File(['test receipt'], 'comprobante.pdf', { type: 'application/pdf' }));
    $('comprobante').files = transfer.files;
    $('comprobante').dispatchEvent(new Event('change'));
    check('Receipt preview restored', !$('receipt-preview').hidden && $('receipt-preview').href.startsWith('blob:'));
    const form = $('checkout-form');
    form.elements.nombre.value = 'Cliente de prueba';
    form.elements.telefono.value = '2321234567';
    form.elements.direccion.value = 'Calle de prueba 123';
    let openedURL = '';
    window.open = url => { openedURL = url; };
    form.requestSubmit();
    check('WhatsApp summary generated without sending', openedURL.startsWith('https://wa.me/522321237364?text=') && decodeURIComponent(openedURL).includes('Cliente de prueba'));
    check('New pending order appended without losing previous order', readOrders().length === 2 && readOrders()[0].cliente === 'Cliente anterior');
    form.requestSubmit();
    check('Repeated handoff does not duplicate order', readOrders().length === 2);
    check('Cart persists after WhatsApp handoff', JSON.parse(localStorage.getItem('miga_cart'))[0].cantidad === 4);
    $('checkout-dialog').close();
    $('open-orders').click();
    check('Customer can view own request only', $('history-dialog').open && $('customer-orders').textContent.includes('Solicitud preparada') && !$('customer-orders').textContent.includes('Cliente anterior'));
    $('history-dialog').close();
    const search = $('search'); search.value = 'cafe'; search.dispatchEvent(new Event('input'));
    check('Search ignores accents', document.querySelectorAll('.product').length > 0 && document.querySelectorAll('.product').length < products.length);
    search.value = ''; search.dispatchEvent(new Event('input'));
    click('[data-category="bebidas"]');
    check('Category filter remains functional', document.querySelectorAll('.product').length === products.filter(p => p.category === 'bebidas').length);
    click('[data-story]');
    check('Expanded stories restored', $('story-dialog').open && $('story-image').src.includes('chocoflan.jpg'));
    $('story-dialog').close();
    const previousSlide = slideIndex;
    $('carousel-next').click();
    check('Carousel navigation restored', slideIndex === (previousSlide + 1) % slides.length);
    carouselPaused = true; scheduleCarousel();
    window.confirm = () => false;
    $('clear-cart').click();
    check('Cancel clear cart preserves contents', cart.length === 1);
    window.confirm = () => true;
    $('clear-cart').click();
    check('Clear cart updates all controls', !cart.length && $('checkout-button').disabled && $('floating-count').textContent === '0');
    check('No horizontal page overflow', document.documentElement.scrollWidth <= innerWidth);
    $('btn-logout').click(); $('login-as-user').click();
    check('Guest entry restored', currentSession.role === 'user' && !$('main-app').hidden);
    check('Original PDF and map preserved', Boolean(document.querySelector('a[download][href^="assets/documents/"]')) && Boolean(document.querySelector('#ubicacion iframe')));
  } catch (error) {
    results.push('FAIL ' + error.message);
  }
  clearInterval(carouselTimer);
  document.querySelectorAll('dialog[open]').forEach(dialog => dialog.close());
  const report = document.createElement('pre');
  report.id = 'verification-results';
  report.textContent = results.join('\n');
  document.body.prepend(report);
  document.title = results.some(result => result.startsWith('FAIL')) ? 'FAIL regression' : 'PASS regression';
  window.scrollTo(0, 0);
});
